sudo: required
services:
    - docker
before_install:
    - docker pull projectdeadlock/embedded-fw-builder
script:
    - docker run -t -v `pwd`:/srv -u `id -u` projectdeadlock/embedded-fw-builder sh -c "cd /srv && make clean && make"
    - docker run -t -v `pwd`:/srv -u `id -u` projectdeadlock/embedded-fw-builder sh -c "cd /srv/docs
                                                                                        && python -m venv _venv
                                                                                        && source _venv/bin/activate
                                                                                        && pip install -r requirements.txt
                                                                                        && make html"
    - docker run -t -v `pwd`:/srv -u `id -u` projectdeadlock/embedded-fw-builder sh -c "cd /srv && make test"
    - docker run -t -v `pwd`:/srv -u `id -u` projectdeadlock/embedded-fw-builder sh -c "cd /srv && make clean && DEBUG_BUILD=no make"
